230503
main_sms :
1. 전화번호 or 메세지 내용이 없어도 성공적으로 db에 입력되는 현상- clear(0504전화번호와 메세지를 다 입력해야 send 버튼이 활성화하는 것으로 설정)
2. tk 위치로 인해 send를 누르기 어려움(위치 조정에 대한 학습이 필요)
3. adb 연결 실패시 기존에 있던 contacts 파일을 사용하는 것으로 수정
    - 연결 성공해야 기존에 있는 파일은 지우는 과정은 만들어져 있음

main.py(/serverfile)
1. Synology에서 돌리려고 만들어졌으나 기기 파이썬에는 너무 많은 제약이 있음
2. 결정해야할 사항 (1. 방법을 찾아서 Synology에서 돌리는 방법 / 2. 사용자 개인 컴퓨터에서 api를 내부망으로 돌리게 하여 휴대폰이 접근 가능하도록 만드는 방법)
   2-2에서의 발생문제
    1. 내부 포트가 겹치는 경우 생각해야함
    2. 현재 user 로그인을 두번하게 되어있음(원래 목적 : 추가작업 없이 1번만 설정 하도록 하는 것)
        1번. 프로그램을 실행할 때
        2번. 외부 기기에서 접근할때 command에서 로그인을 요구-clear(0504 최근 로그인을 config.json에 입력받아서 자동으로 로그인하도록 설정함)
3. db가 변경될 경우
    db 변경시 api도 바로 변경되도록 설정했지만 일정 수준 사용하면 연결이 초기화 되는 현상
    이경우 연결 다시하도록 설정하거나 하는 코드가 필요할 것으로 보임
    - 현재 제일 문제되는 부분임 우선 증가한 문제는
        1. db로 모든게 넘어갔을 때 처음에 api_server.py만 restart하면 될줄 알았음 - 실패
        2. 이유는 restart를 하더라도 0.0.0.0:8000 포트가 kill되지 않고 살아있기때문(?) 그래서 restart_another_script 내부에 server.close()를 작성해봤지만
            python_sms.py 자체가 재실행되는 현상이 발생함 (db 로그인을 다시 처음부터 받기 시작하는 것으로 알 수 있었음)
        3. 현재 일단은 api_server를 restart 시키는거 자체는 구현을 했지만 정작 python_sms에서 코드가 이상해졌음
            발견된 문제
                1. python_sms를 실행시 api_server를 같이 시작하도록 설정하였음
                2. restart_another_script의 정의 부분에 매개변수 server에대한 설정이 api_server의 start_server함수를 실행시켜야 반환되는데
                    이부분에서 오류가 나오는 것으로 추정됨

